spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lovecheng/springcloud_study
          username: chlin7@126.com
          password: chenhualin1990
          # 配置本地服务器缓存存储路径
          basedir: E:/workspace/idea/imooc/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8777

